import 'dart:typed_data';
import 'package:excel/excel.dart';
import 'package:file_saver/file_saver.dart';
import 'package:intl/intl.dart';

import '../repositories/accounting_repository.dart';

class ExcelExportService {
  /// Generates and saves the General Ledger as an Excel (.xlsx) file.
  static Future<void> exportLedger({
    required String? outletName,
    required String userName,
    required AccountingTotals totals,
    required List<LedgerEntry> entries,
  }) async {
    final excel = Excel.createExcel();
    
    // ── SUMMARY SHEET ──
    final summarySheet = excel['Summary'];
    excel.setDefaultSheet('Summary');
    
    // Header Info
    final dateStr = DateFormat('dd MMM yyyy, HH:mm').format(DateTime.now());
    final displayOutlet = outletName ?? 'All Outlets';
    
    summarySheet.appendRow([TextCellValue('General Ledger Report')]);
    summarySheet.appendRow([TextCellValue('Outlet'), TextCellValue(displayOutlet)]);
    summarySheet.appendRow([TextCellValue('Generated Date'), TextCellValue(dateStr)]);
    summarySheet.appendRow([TextCellValue('Generated By'), TextCellValue(userName)]);
    summarySheet.appendRow([TextCellValue('')]);
    
    // Format bold headers for Summary
    final boldStyle = CellStyle(bold: true);
    for (int i = 0; i < 4; i++) {
      summarySheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: i)).cellStyle = boldStyle;
    }
    summarySheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: 0)).cellStyle = CellStyle(bold: true, fontSize: 14);

    // Totals Table
    summarySheet.appendRow([TextCellValue('Total Ledger Entries'), IntCellValue(totals.totalLedgerEntries)]);
    summarySheet.appendRow([TextCellValue('Total Journal Entries'), IntCellValue(totals.totalJournalEntries)]);
    summarySheet.appendRow([TextCellValue('Total Debit'), DoubleCellValue(totals.totalDebit)]);
    summarySheet.appendRow([TextCellValue('Total Credit'), DoubleCellValue(totals.totalCredit)]);
    summarySheet.appendRow([TextCellValue('Net Balance'), DoubleCellValue(totals.netBalance)]);
    summarySheet.appendRow([TextCellValue('Status'), TextCellValue(totals.isBalanced ? 'Balanced ✓' : 'Unbalanced ✗')]);

    for (int i = 5; i <= 10; i++) {
      summarySheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: i)).cellStyle = boldStyle;
    }

    // Auto fit column widths roughly
    summarySheet.setColumnWidth(0, 25);
    summarySheet.setColumnWidth(1, 30);


    // ── TRANSACTIONS SHEET ──
    final txSheet = excel['Transaction Details'];
    
    // Header row
    txSheet.appendRow([
      TextCellValue('Date'),
      TextCellValue('Description'),
      TextCellValue('Account Code'),
      TextCellValue('Account Name'),
      TextCellValue('Debit'),
      TextCellValue('Credit'),
      TextCellValue('Outlet'),
    ]);
    
    for (int c = 0; c < 7; c++) {
      txSheet.cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: 0)).cellStyle = boldStyle;
    }
    
    // Add data rows
    for (final e in entries) {
      txSheet.appendRow([
        TextCellValue(DateFormat('yyyy-MM-dd HH:mm').format(e.date.toLocal())),
        TextCellValue(e.description),
        TextCellValue(e.accountCode),
        TextCellValue(e.accountName),
        DoubleCellValue(e.debit),
        DoubleCellValue(e.credit),
        TextCellValue(e.outletName ?? '-'),
      ]);
    }
    
    // Set some widths
    txSheet.setColumnWidth(0, 20);
    txSheet.setColumnWidth(1, 40);
    txSheet.setColumnWidth(2, 15);
    txSheet.setColumnWidth(3, 25);
    txSheet.setColumnWidth(4, 15);
    txSheet.setColumnWidth(5, 15);
    txSheet.setColumnWidth(6, 25);

    // Hapus sheet bawaan 'Sheet1' yang kosong
    excel.delete('Sheet1');
    
    // ── SAVE FILE ──
    final fileBytes = excel.encode();
    if (fileBytes == null) throw Exception("Failed to generate Excel file.");

    final safeOutletName = displayOutlet.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
    final dateStamp = DateFormat('yyyy-MM-dd').format(DateTime.now());
    final fileName = 'Accounting_Report_${safeOutletName}_$dateStamp';

    await FileSaver.instance.saveFile(
      name: '$fileName.xlsx',
      bytes: Uint8List.fromList(fileBytes),
      mimeType: MimeType.microsoftExcel,
    );
  }
}
